apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          #image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          image: httpd  ## NOTE: test using the pretend app
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB_VENDOR
            value: {{ .Values.database.vendor }}
          - name: DB_HOST
            value: {{ .Values.database.host }}
          - name: DB_PORT
            value: {{ .Values.database.port | quote }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.secret }}
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.secret }}
                key: DB_PASSWORD
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
