replicaCount: 1

image:
  repository: httpd           # pretend app, it prints "It works!" by default
  pullPolicy: Always

service:
  name: friendly-app-svc
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080 

ingress:
  enabled: false
  hosts:
    - host: archops.localnet
      paths:
        - path: /

volumeMounts:
 - volume: friendly-pv
   claim: friendly-pvc
   mountPath: "/data"
   nfsserver: cloud10.localnet
   nfsmount: /Public/data
